# SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception
# Copyright (c) 2023-2026 Dismo Industries LLC
"""Generate lib/TrustedRoots/TrustedRootsData.cpp from lib/TrustedRoots/roots/.

roots/roots.json lists each root's DER file, name, SHA-256, source and the
protected host it serves. Every file must hash to its listed SHA-256 and be
exactly one DER certificate, or nothing is written.

    python tools/trusted-roots/generate.py           # rewrite the C++ table
    python tools/trusted-roots/generate.py --check   # exit 1 if it is stale

Standard library only.
"""

import argparse
import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ROOTS_DIR = REPO / "lib" / "TrustedRoots" / "roots"
OUTPUT = REPO / "lib" / "TrustedRoots" / "TrustedRootsData.cpp"


def load_manifest():
    with open(ROOTS_DIR / "roots.json", encoding="utf-8") as f:
        return json.load(f)


def der_length(der):
    """Total length of the outer DER SEQUENCE, or -1 if it is not one."""
    if len(der) < 2 or der[0] != 0x30:
        return -1
    first = der[1]
    if first < 0x80:
        return 2 + first
    count = first & 0x7F
    if count == 0 or count > 4 or len(der) < 2 + count:
        return -1
    return 2 + count + int.from_bytes(der[2:2 + count], "big")


def load_roots(manifest):
    """[(entry, der bytes)] after checking every file against the manifest."""
    roots = []
    for entry in manifest["roots"]:
        der = (ROOTS_DIR / entry["file"]).read_bytes()
        digest = hashlib.sha256(der).hexdigest()
        if digest != entry["sha256"].lower():
            sys.exit(f"{entry['file']}: SHA-256 {digest} does not match roots.json {entry['sha256']}")
        if der_length(der) != len(der):
            sys.exit(f"{entry['file']}: not exactly one DER certificate")
        roots.append((entry, der))
    return roots


def identifier(file_name):
    stem = file_name.rsplit(".", 1)[0]
    return "k" + "".join(part[:1].upper() + part[1:] for part in stem.split("-"))


def c_string(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render(roots):
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception",
        "// Copyright (c) 2023-2026 Dismo Industries LLC",
        "//",
        "// GENERATED by tools/trusted-roots/generate.py from lib/TrustedRoots/roots/.",
        "// Do not edit: change roots/roots.json and the .der files, then rerun it.",
        "",
        '#include "TrustedRoots.h"',
        "",
        "namespace TrustedRoots {",
        "namespace {",
        "",
    ]
    for entry, der in roots:
        lines += [
            f"// {entry['name']} ({len(der)} B)",
            f"//   SHA-256: {entry['sha256'].lower()}",
            f"//   Source:  {entry['source']}",
            f"//   Checked: {entry['checked']}",
            f"//   Why:     {entry['protects']}",
            f"const uint8_t {identifier(entry['file'])}[] = {{",
        ]
        for i in range(0, len(der), 16):
            lines.append("    " + " ".join(f"0x{b:02x}," for b in der[i:i + 16]))
        lines += ["};", ""]
    lines += ["}  // namespace", "", "const Root kRoots[] = {"]
    for entry, der in roots:
        name = identifier(entry["file"])
        lines.append(f'    {{"{c_string(entry["name"])}", {name}, sizeof({name}),')
        lines.append(f'     "{entry["sha256"].lower()}"}},')
    lines += [
        "};",
        "const size_t kRootCount = sizeof(kRoots) / sizeof(kRoots[0]);",
        "",
        "}  // namespace TrustedRoots",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if TrustedRootsData.cpp does not match roots/")
    args = parser.parse_args()

    roots = load_roots(load_manifest())
    text = render(roots)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(REPO)} is stale; run tools/trusted-roots/generate.py")
            return 1
        print(f"{OUTPUT.relative_to(REPO)} is current ({len(roots)} roots)")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    total = sum(len(der) for _, der in roots)
    print(f"wrote {OUTPUT.relative_to(REPO)}: {len(roots)} roots, {total} B of DER")
    return 0


if __name__ == "__main__":
    sys.exit(main())
