// SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception
// Copyright (c) 2023-2026 Dismo Industries LLC

// lib/CFGraphics/test/fixtures/generate_cf_gfx_mesh_golden.cpp
//
// Rebuild from the worktree root:
//   g++ -std=gnu++17 -DHOST_TEST=1 -I lib/CFGraphics/include -I lib/CFGraphics/test/fixtures lib/CFGraphics/test/fixtures/generate_cf_gfx_mesh_golden.cpp -o lib/CFGraphics/test/fixtures/generate_cf_gfx_mesh_golden
//   lib/CFGraphics/test/fixtures/generate_cf_gfx_mesh_golden
//
// This generator renders each pose once, then writes both committed formats
// from the same recorded points, drawLine calls, and framebuffer.

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "cf_gfx_mesh_ship_fixture.h"

using namespace cf::gfx;
using namespace cf::gfx::meshfixtures;

namespace {

struct PoseSpec {
    uint8_t yaw;
    uint8_t pitch;
    uint8_t roll;
    uint16_t scaleQ8;
    uint8_t depth;
};

struct PointResult {
    uint8_t index;
    bool visible;
    int16_t x;
    int16_t y;
};

struct PoseResult {
    PoseSpec spec;
    std::vector<PointResult> points;
    std::vector<DisplayProxy::LineCall> lines;
    uint8_t framebuffer[1024];
};

const PoseSpec kPoses[] = {
    { 0,   0,   0, 256, 48},
    {32,   0,   0, 256, 48},
    {64,   0,   0, 256, 48},
    { 0, 238,   0, 256, 48},
    {96, 238,   0, 256, 48},
    { 0,   0,  32, 256, 48},
    {32, 238,  16, 384, 32},
    {40,  16, 200, 192,  0},
};

PoseResult render(const PoseSpec& spec) {
    MeshActor actor;
    actor.setMesh(&ship_mesh);
    actor.setPos(64, 32);
    actor.setScaleQ8(spec.scaleQ8);
    actor.setRotation(spec.yaw, spec.pitch, spec.roll);
    actor.setPerspective(spec.depth);

    PoseResult result = {};
    result.spec = spec;
    for (uint8_t i = 0; i < ship_mesh.vertCount; ++i) {
        int16_t x = 0;
        int16_t y = 0;
        const MeshVertex& v = ship_mesh.verts[i];
        const bool visible = actor.projectPoint(v.x, v.y, v.z, x, y);
        result.points.push_back(PointResult{i, visible, x, y});
    }

    DisplayProxy display;
    actor.draw(display);
    for (int i = 0; i < display.lineCount; ++i) {
        result.lines.push_back(display.lines[i]);
    }
    for (int i = 0; i < 1024; ++i) {
        result.framebuffer[i] = display.fb[i];
    }
    return result;
}

void writeByteArray(std::ostream& out, const uint8_t* bytes) {
    for (int i = 0; i < 1024; ++i) {
        if ((i & 15) == 0) out << "    ";
        out << static_cast<unsigned>(bytes[i]);
        if (i != 1023) out << ",";
        if ((i & 15) == 15) out << "\n"; else out << " ";
    }
}

void writeHeader(const std::vector<PoseResult>& results,
                 const std::string& path) {
    std::ofstream out(path.c_str(), std::ios::binary);
    out << "// SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception\n"
        << "// Copyright (c) 2023-2026 Dismo Industries LLC\n\n"
        << "// lib/CFGraphics/test/fixtures/cf_gfx_mesh_golden.h\n"
        << "// Generated by generate_cf_gfx_mesh_golden.cpp. Do not hand-edit.\n\n"
        << "#ifndef CF_GFX_MESH_GOLDEN_H\n"
        << "#define CF_GFX_MESH_GOLDEN_H\n\n"
        << "#include <stdint.h>\n\n"
        << "namespace cf { namespace gfx { namespace meshgolden {\n\n"
        << "struct GoldenPoint { uint8_t index; bool visible; int16_t x; int16_t y; };\n"
        << "struct GoldenLine { int16_t x0; int16_t y0; int16_t x1; int16_t y1; };\n"
        << "struct GoldenPose {\n"
        << "    uint8_t index, yaw, pitch, roll;\n"
        << "    uint16_t scaleQ8;\n"
        << "    uint8_t depth;\n"
        << "    int16_t anchorX, anchorY;\n"
        << "    const GoldenPoint* points;\n"
        << "    uint8_t pointCount;\n"
        << "    const GoldenLine* lines;\n"
        << "    uint8_t lineCount;\n"
        << "    const uint8_t* framebuffer;\n"
        << "};\n\n";

    for (size_t p = 0; p < results.size(); ++p) {
        const PoseResult& result = results[p];
        out << "inline constexpr GoldenPoint pose_" << p << "_points[] = {\n";
        for (const PointResult& point : result.points) {
            out << "    {" << static_cast<unsigned>(point.index) << ", "
                << (point.visible ? "true" : "false") << ", "
                << point.x << ", " << point.y << "},\n";
        }
        out << "};\n\n";

        out << "inline constexpr GoldenLine pose_" << p << "_lines[] = {\n";
        for (const DisplayProxy::LineCall& line : result.lines) {
            out << "    {" << line.x0 << ", " << line.y0 << ", "
                << line.x1 << ", " << line.y1 << "},\n";
        }
        out << "};\n\n";

        out << "inline constexpr uint8_t pose_" << p
            << "_framebuffer[1024] = {\n";
        writeByteArray(out, result.framebuffer);
        out << "};\n\n";
    }

    out << "inline constexpr GoldenPose poses[] = {\n";
    for (size_t p = 0; p < results.size(); ++p) {
        const PoseResult& result = results[p];
        out << "    {" << p << ", "
            << static_cast<unsigned>(result.spec.yaw) << ", "
            << static_cast<unsigned>(result.spec.pitch) << ", "
            << static_cast<unsigned>(result.spec.roll) << ", "
            << result.spec.scaleQ8 << ", "
            << static_cast<unsigned>(result.spec.depth)
            << ", 64, 32, pose_" << p << "_points, "
            << result.points.size() << ", pose_" << p << "_lines, "
            << result.lines.size() << ", pose_" << p << "_framebuffer},\n";
    }
    out << "};\n\n"
        << "inline constexpr uint8_t pose_count = "
        << results.size() << ";\n\n"
        << "}}}  // namespace cf::gfx::meshgolden\n\n"
        << "#endif  // CF_GFX_MESH_GOLDEN_H\n";
}

std::string framebufferHex(const uint8_t* bytes) {
    std::ostringstream out;
    out << std::hex << std::setfill('0');
    for (int i = 0; i < 1024; ++i) {
        out << std::setw(2) << static_cast<unsigned>(bytes[i]);
    }
    return out.str();
}

void writeJson(const std::vector<PoseResult>& results,
               const std::string& path) {
    std::ofstream out(path.c_str(), std::ios::binary);
    out << "{\n"
        << "  \"schemaVersion\": 1,\n"
        << "  \"generatedBy\": \"cf::gfx mesh runtime\",\n"
        << "  \"framebuffer\": { \"width\": 128, \"height\": 64, "
        << "\"layout\": \"byte = x + (y >> 3) * 128, bit = y & 7, set = lit\" },\n"
        << "  \"mesh\": {\n"
        << "    \"name\": \"ship\",\n"
        << "    \"verts\": [";
    for (uint8_t i = 0; i < ship_mesh.vertCount; ++i) {
        const MeshVertex& v = ship_mesh.verts[i];
        if (i != 0) out << ", ";
        out << "[" << static_cast<int>(v.x) << "," << static_cast<int>(v.y)
            << "," << static_cast<int>(v.z) << "]";
    }
    out << "],\n    \"edges\": [";
    for (uint16_t i = 0; i < ship_mesh.edgeCount; ++i) {
        if (i != 0) out << ", ";
        out << "[" << static_cast<unsigned>(ship_mesh.edges[i][0]) << ","
            << static_cast<unsigned>(ship_mesh.edges[i][1]) << "]";
    }
    out << "]\n  },\n  \"poses\": [\n";

    for (size_t p = 0; p < results.size(); ++p) {
        const PoseResult& result = results[p];
        out << "    { \"index\": " << p
            << ", \"yaw\": " << static_cast<unsigned>(result.spec.yaw)
            << ", \"pitch\": " << static_cast<unsigned>(result.spec.pitch)
            << ", \"roll\": " << static_cast<unsigned>(result.spec.roll)
            << ", \"scaleQ8\": " << result.spec.scaleQ8
            << ", \"depth\": " << static_cast<unsigned>(result.spec.depth)
            << ", \"anchorX\": 64, \"anchorY\": 32,\n"
            << "      \"points\": [";
        for (size_t i = 0; i < result.points.size(); ++i) {
            const PointResult& point = result.points[i];
            if (i != 0) out << ", ";
            out << "{\"i\":" << static_cast<unsigned>(point.index)
                << ",\"visible\":" << (point.visible ? "true" : "false");
            if (point.visible) {
                out << ",\"x\":" << point.x << ",\"y\":" << point.y;
            }
            out << "}";
        }
        out << "],\n      \"lines\": [";
        for (size_t i = 0; i < result.lines.size(); ++i) {
            const DisplayProxy::LineCall& line = result.lines[i];
            if (i != 0) out << ", ";
            out << "[" << line.x0 << "," << line.y0 << ","
                << line.x1 << "," << line.y1 << "]";
        }
        out << "],\n      \"framebufferHex\": \""
            << framebufferHex(result.framebuffer) << "\" }\n";
        if (p + 1 != results.size()) out << "    ,\n";
    }
    out << "  ]\n}\n";
}

}  // namespace

int main() {
    std::vector<PoseResult> results;
    for (const PoseSpec& pose : kPoses) results.push_back(render(pose));

    const std::string base = "lib/CFGraphics/test/fixtures/";
    const std::string headerPath = base + "cf_gfx_mesh_golden.h";
    const std::string jsonPath = base + "cf_gfx_mesh_golden.json";
    writeHeader(results, headerPath);
    writeJson(results, jsonPath);
    std::cout << "wrote " << headerPath << "\n"
              << "wrote " << jsonPath << "\n";
    return 0;
}
