# SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception
# Copyright (c) 2023-2026 Dismo Industries LLC
"""Convert a .wasm binary into an embeddable C header (xxd -i style).

Usage: python wasm2header.py <input.wasm> <output.h> <symbol_name>

The generated array is const (lives in flash rodata, memory-mapped on ESP32,
so wasm3 can parse/execute it in place without a RAM copy) and 4-byte aligned.
"""
import sys


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 1
    in_path, out_path, sym = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(in_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append("// Auto-generated by wasm/device_module/wasm2header.py -- DO NOT EDIT.")
    lines.append("// Source: %s (%d bytes). Rebuild via build_device_modules.bat." % (
        in_path.replace("\\", "/").split("/")[-1], len(data)))
    lines.append("#ifndef %s_H" % sym.upper())
    lines.append("#define %s_H" % sym.upper())
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("__attribute__((aligned(4))) static const uint8_t %s[] = {" % sym)
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + " ".join("0x%02x," % b for b in chunk))
    lines.append("};")
    lines.append("")
    lines.append("static const size_t %s_len = sizeof(%s);" % (sym, sym))
    lines.append("")
    lines.append("#endif  // %s_H" % sym.upper())
    lines.append("")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d bytes of wasm)" % (out_path, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
